name: Deploy Microservices

on:
  push:
    branches: [ "main" ]
    paths:
      - "users-service/**"
      - "orders-service/**"
      - "inventory-service/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: demo

    env:
      REGISTRY: microshopacr.azurecr.io
      RESOURCE_GROUP: microshop-rg
      CLUSTER_NAME: microshop-aks
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and Push Users
        run: |
          az acr login --name $REGISTRY
          docker build -t $REGISTRY/users:${{ github.sha }} ./users
          docker push $REGISTRY/users:${{ github.sha }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Deploy Users
        run: |
          kubectl set image deployment/users-deployment users=$REGISTRY/users:${{ github.sha }}
          kubectl rollout status deployment/users-deployment
