name: Deploy Microservices

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      REGISTRY_NAME: microshopacr
      REGISTRY: microshopacr.azurecr.io
      RESOURCE_GROUP: microshop-rg
      CLUSTER_NAME: microshop-aks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds:${{secrets.AZURE_CREDENTIALS}}

      - name: Login to ACR
        run: |
          az acr login --name $REGISTRY_NAME

     
      # BUILD & PUSH IMAGES
      - name: Build & Push Users Service
        run: |
          docker build -t $REGISTRY/users-service:${{ github.sha }} ./users-service
          docker push $REGISTRY/users-service:${{ github.sha }}

      - name: Build & Push Orders Service
        run: |
          docker build -t $REGISTRY/orders-service:${{ github.sha }} ./orders-service
          docker push $REGISTRY/orders-service:${{ github.sha }}

      - name: Build & Push Inventory Service
        run: |
          docker build -t $REGISTRY/inventory-service:${{ github.sha }} ./inventory-service
          docker push $REGISTRY/inventory-service:${{ github.sha }}

      # CONNECT TO AKS
      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $CLUSTER_NAME \
            --overwrite-existing

      # APPLY MANIFESTS (CREATES IF NOT EXISTS)
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f users-service/deployment.yaml
          kubectl apply -f orders-service/deployment.yaml
          kubectl apply -f inventory-service/deployment.yaml

      # UPDATE IMAGES
      - name: Update Users Deployment
        run: |
          kubectl set image deployment/users-service users=$REGISTRY/users-service:${{ github.sha }}
          kubectl rollout status deployment/users-service

      - name: Update Orders Deployment
        run: |
          kubectl set image deployment/orders-service orders=$REGISTRY/orders-service:${{ github.sha }}
          kubectl rollout status deployment/orders-service

      - name: Update Inventory Deployment
        run: |
          kubectl set image deployment/inventory-service inventory=$REGISTRY/inventory-service:${{ github.sha }}
          kubectl rollout status deployment/inventory-service
