name: Deploy Microservices

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: demo

    env:
      REGISTRY_NAME: microshopacr
      REGISTRY: microshopacr.azurecr.io
      RESOURCE_GROUP: microshop-rg
      CLUSTER_NAME: microshop-aks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Users
        run: |
          az acr login --name $REGISTRY_NAME
          docker build -t $REGISTRY/users:${{ github.sha }} ./users-service
          docker push $REGISTRY/users:${{ github.sha }}

      - name: Build and Push Orders
        run: |
          docker build -t $REGISTRY/orders:${{ github.sha }} ./orders-service
          docker push $REGISTRY/orders:${{ github.sha }}

      - name: Build and Push Inventory
        run: |
          docker build -t $REGISTRY/inventory:${{ github.sha }} ./inventory-service
          docker push $REGISTRY/inventory:${{ github.sha }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Deploy Users
        run: |
          kubectl set image deployment/users-deployment users=$REGISTRY/users:${{ github.sha }}
          kubectl rollout status deployment/users-deployment

      - name: Deploy Orders
        run: |
          kubectl set image deployment/orders-deployment orders=$REGISTRY/orders:${{ github.sha }}
          kubectl rollout status deployment/orders-deployment

      - name: Deploy Inventory
        run: |
          kubectl set image deployment/inventory-deployment inventory=$REGISTRY/inventory:${{ github.sha }}
          kubectl rollout status deployment/inventory-deployment
