name: Setup Ingress

on:
  workflow_dispatch:   # manual trigger

jobs:
  apply-ingress:
    runs-on: ubuntu-latest
    environment: demo

    env:
      RESOURCE_GROUP: microshop-rg
      CLUSTER_NAME: microshop-aks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Add Helm Repo
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Create Namespace
        run: |
          kubectl get namespace ingress-basic || kubectl create namespace ingress-basic

      - name: Install NGINX Ingress Controller
        run: |
          helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx \
            --namespace ingress-basic \
            --set controller.replicaCount=2 \
            --set controller.nodeSelector."kubernetes\\.io/os"=linux \
            --set defaultBackend.nodeSelector."kubernetes\\.io/os"=linux

      - name: Apply Ingress
        run: |
          kubectl apply -f k8s/ingress.yaml
