name: Setup Ingress

on:
  workflow_dispatch:   # manual trigger

jobs:
  apply-ingress:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: microshop-rg
      CLUSTER_NAME: microshop-aks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Apply Ingress
        run: |
          kubectl apply -f k8s/ingress.yaml
